---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: podinfo
resources: 
  - ../base
patches:
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: podinfo
        namespace: podinfo
      spec:
        minReplicas: 3
#  - path: ./horizontalPodScaler.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: podinfo
targetNamespace: podinfo

