---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: podinfo
resources: 
  - ../base
patches:
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: podinfo
        namespace: podinfo
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: podinfo
        minReplicas: 3
        maxReplicas: 5
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              # scale up if usage is above
              # 99% of the requested CPU (100m)
              averageUtilization: 99
#  - path: ./horizontalPodScaler.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: podinfo

