apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-staging
  namespace: flux-system
resources: 
  - ../base
spec:
  patches: 
    - patch: |-
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: ingress-route
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
        spec:
          rules:
          - host: localhost
            http:
              paths:
              - path: /
                pathType: Prefix
                podinfo:
                  service:
                    name: podinfo
                    port:
                      number: 9898
      target:
        kind: Ingress
sourceRef: 
  kind: GitRepository
  name: podinfo
prune: true
path: ./kustomize
targetNamespace: default
wait: true