apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-staging
  namespace: flux-system
resources: 
  - ../base
  - ./podinfo-ingress.yaml
sourceRef: 
  kind: GitRepository
  name: podinfo
prune: true
path: ./kustomize
targetNamespace: default
wait: true