apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: podinfo
spec:
  interval: 3m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: ./kustomize
  targetNamespace: podinfo
  prune: true
  wait: true
  timeout: 5m0s